name: gdscvit_icebreaker
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_ui_firestore: ^1.5.1
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_lint: ^1.3.2
  custom_lint: ^0.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: RubikPuddles
      fonts:
        - asset: assets/fonts/RubikPuddles-Regular.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic
